Controllers/CarrinhoCompraController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetPants.Models;
using NetPants.Repositories.Interfaces;
using NetPants.ViewModels;

namespace NetPants.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly IRoupaRepository _roupaRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IRoupaRepository roupaRepository, 
            CarrinhoCompra carrinhoCompra)
        {
            _roupaRepository = roupaRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };
            return View(carrinhoCompraVM);
        }

        [Authorize]
        public IActionResult AdicionarItemNoCarrinhoCompra(int roupaId)
        {
            var roupaSelecionada = _roupaRepository.Roupas.FirstOrDefault(p => p.RoupaId == roupaId);
            if(roupaSelecionada != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(roupaSelecionada);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult RemoverItemDoCarrinhoCompra(int roupaId)
        {
            var roupaSelecionada = _roupaRepository.Roupas.FirstOrDefault(p => p.RoupaId == roupaId);
            if (roupaSelecionada != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(roupaSelecionada);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/RoupaController.cs
using Microsoft.AspNetCore.Mvc;
using NetPants.Models;
using NetPants.Repositories.Interfaces;
using NetPants.ViewModels;

namespace NetPants.Controllers
{
    public class RoupaController : Controller
    {
        private readonly IRoupaRepository _roupaRepository;

        public RoupaController(IRoupaRepository roupaRpository)
        {
            _roupaRepository = roupaRpository;
        }

        public IActionResult List(string categoria)
        {
            IEnumerable<Roupa> roupas;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(categoria))
            {
                roupas = _roupaRepository.Roupas.OrderBy(l => l.RoupaId);
                categoriaAtual = "Todas as Roupas";
            }
            else
            {
                //if(string.Equals("Roupas", categoria, StringComparison.OrdinalIgnoreCase))
                //{
                //    roupas = _roupaRepository.Roupas
                //        .Where(l => l.Categoria.CategoriaNome.Equals("Roupas"))
                //        .OrderBy(l => l.Nome);
                //}
                //else
                //{
                //    roupas = _roupaRepository.Roupas
                //       .Where(l => l.Categoria.CategoriaNome.Equals("Calçados"))
                //       .OrderBy(l => l.Nome);
                //}

                roupas = _roupaRepository.Roupas
                    .Where(l => l.Categoria.CategoriaNome.Equals(categoria))
                    .OrderBy(c => c.Nome);

                categoriaAtual = categoria;
            }
            var roupasListViewModel = new RoupaListViewModel
            {
                Roupas = roupas,
                CategoriaAtual = categoriaAtual
            };

            return View(roupasListViewModel);
        }

        public IActionResult Details(int roupaId)
        {
            var roupa = _roupaRepository.Roupas.FirstOrDefault(l => l.RoupaId == roupaId);
            return View(roupa);
        }

        public ViewResult Search(string searchString)
        {
            IEnumerable<Roupa> roupas;
            string categoriaAtual = string.Empty;

            if (string.IsNullOrEmpty(searchString))
            {
                roupas = _roupaRepository.Roupas.OrderBy(p => p.RoupaId);
                categoriaAtual = "Todas as Roupas";
            }
            else
            {
                roupas = _roupaRepository.Roupas
                    .Where(p => p.Nome.ToLower().Contains(searchString.ToLower()));

                if (roupas.Any())
                    categoriaAtual = "Roupas";
                else
                    categoriaAtual = "Nenhum produto foi encontrado";
            }
            return View("~/Views/Roupa/List.cshtml", new RoupaListViewModel
            {
                Roupas = roupas,
                CategoriaAtual = categoriaAtual
            });

        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - NetPants</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/NetPants.styles.css" asp-append-version="true" />
    
</head>
<body>
    <header>
        <nav style="background-color: #101010; height: 120px; align-items: center; display: flex; justify-content: space-around; color: white; border-bottom: 1px solid white">
            <div class="container">
                <div class="row">
                    <!--Logo-->
                    <div class="col-1" style="align-items: center; display: flex; justify-content: space-around; letter-spacing: 1px;">
                        <a class="" style="text-decoration: none; font-family:'Copperplate Gothic'; color: white; font-size: 40px" asp-area="" asp-controller="Home" asp-action="Index">Pants</a>
                    </div>

                    <!--Categorias-->
                    <div class="col-7" style="align-items: center; display: flex; justify-content: space-around">
                        @await Component.InvokeAsync("CategoriaMenu")
                    </div>

                    <!--Pesquisa-->
                    <div class="col-2" style="align-items: center; display: flex; justify-content: space-around">
                        <form class="navbar-form" asp-controller="Roupa" asp-action="Search" method="get">
                            <div class="" style="display: flex; justify-content: space-between; align-items: center">
                                <input type="text" style="outline: 0; color: black" placeholder="Buscar" name="searchString" required  value="@ViewData["searchString"]" />
                                
                                <button value="@ViewData["searchString"]" style="background-color: white; padding: 2px">
                                        <img src="~/images/pesquisa.png" alt="" style="width: 22px; height: 22px; margin-left: " />
                                </button>
                            </div>
                        </form>
                    </div>

                    <!--Login-->
                    <div id="login_hover" class="col-1" style="align-items: center; display: flex; justify-content: space-around">
                        @await Html.PartialAsync("_LoginPartial")
                        @if (User.IsInRole("Admin"))
                        {
                            <a class="nav-link text-light" asp-area="Admin" asp-controller="Admin" asp-action="Index">Admin</a>
                        }
                    </div>

                    <!--Sacola-->
                    <div id="sacola_hover" class="col-1" style="align-items: center; display: flex; justify-content: space-around">
                        <a class="nav-link text-light" asp-controller="CarrinhoCompra" asp-action="Index" asp-route-returnUrl="" style="color:white"><img src="~/images/sacola.png" style="width: 25px" /></a>

                    </div>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - Pants - Desenvolvido por Pedro Henrique <a asp-area="" asp-controller="Home" asp-action="Index">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Views/Shared/_RoupasResumo.cshtml
@model Roupa
<link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />

<div class="col-sm-4 col-md-4 col-lg-4">
    <div class="">
    <a asp-controller="Roupa" asp-action="Details" asp-route-roupaId="@Model.RoupaId"><img id="icone" src="@Model.ImagemUrl" class="img-fluid" style="width: 280px" /></a>
    </div>
    


    <h5 class="ofertas">
        <a style="text-decoration: none; color: black" asp-controller="Roupa" asp-action="Details"
    asp-route-roupaId="@Model.RoupaId">@Model.DescricaoCurta</a>
    </h5>

    <h6>@Model.DescricaoCurta</h6>

    <h6>@Model.Marca</h6>

    <h6>@Model.Preco.ToString("c")</h6>

    <div style="padding-bottom: 50px; padding-top: 10px">
        <p class="button">
            <a class="btn btn-primary" id="cartButton" asp-controller="Roupa"
            asp-action="details" asp-route-RoupaId="@Model.RoupaId">
            Mais Detalhes
            </a>
        </p>
    </div>

</div>

Views/Shared/_carousel.cshtml
<div container>

    <div>
        <img src="~/images/body.png" style="width: 2000px; margin-left: -355px"/>
    </div>

    <div style="align-items: center; display: flex; justify-content: space-around; margin: 50px 0; padding: 15px 0 ;background-color: #CECECE; border-radius: 10px; border: 1px solid #E6E6E6">

        <div style="">
            <img src="~/images/caminhao.png" style="align-items: center; display: flex; justify-content: space-around; padding-left: 20px"/>
            <h6>Frete grátis</h6>
        </div>

        <div style="">
            <img src="~/images/entrega.png" style="align-items: center; display: flex; justify-content: space-around; padding-left: 30px" />
            <h6>Entrega rápida</h6>
        </div>

        <div style="">
            <img src="~/images/cartao.png" style="align-items: center; display: flex; justify-content: space-around; padding-left: 40px" />
            <h6>Até 6x sem Juros</h6>
        </div>

        <div style="">
            <img src="~/images/tag.png" style="align-items: center; display: flex; justify-content: space-around; padding-left: 40px" />
            <h6>Melhores preços</h6>
        </div>

        <div style="">
            <img src="~/images/shopping.png" style="align-items: center; display: flex; justify-content: space-around; padding-left: 40px" />
            <h6>Melhores marcas</h6>
        </div>
    </div>

    <div>
        <img src="~/images/body_zatini.png" style="width: 2000px; margin-left: -355px" />
    </div>
</div>