Models/CarrinhoCompra.cs
using Microsoft.EntityFrameworkCore;
using NetPants.Context;

namespace NetPants.Models
{
    public class CarrinhoCompra
    {

        private readonly AppDbContext _context;

        public CarrinhoCompra(AppDbContext context)
        {
            _context = context;
        }

        public string CarrinhoCompraId { get; set; }
        public List<CarrinhoCompraItem> CarrinhoCompraItems { get; set; }

        public static CarrinhoCompra GetCarrinho(IServiceProvider services)
        {
            ISession session = services.GetRequiredService<IHttpContextAccessor>()?.HttpContext.Session;

            var context = services.GetService<AppDbContext>();

            string carrinhoId = session.GetString("CarrinhoId") ?? Guid.NewGuid().ToString();

            session.SetString("CarrinhoId", carrinhoId);

            return new CarrinhoCompra(context)
            {
                CarrinhoCompraId = carrinhoId
            };
        }

        public void AdicionarAoCarrinho(Roupa roupa)
        {
            var carrinhoCompraItem = _context.CarrinhoCompraItens.SingleOrDefault(
                s => s.Roupa.RoupaId == roupa.RoupaId &&
                s.CarrinhoCompraId == CarrinhoCompraId);

            if(carrinhoCompraItem == null)
            {
                carrinhoCompraItem = new CarrinhoCompraItem
                {
                    CarrinhoCompraId = CarrinhoCompraId,
                    Roupa = roupa,
                    Quantidade = 1
                };
                _context.CarrinhoCompraItens.Add(carrinhoCompraItem);
            }
            else
            {
                carrinhoCompraItem.Quantidade++;
            }
            _context.SaveChanges();
        }

        public int RemoverDoCarrinho(Roupa roupa)
        {
            var carrinhoCompraItem = _context.CarrinhoCompraItens.SingleOrDefault(
               s => s.Roupa.RoupaId == roupa.RoupaId &&
               s.CarrinhoCompraId == CarrinhoCompraId);

            var quantidadeLocal = 0;

            if(carrinhoCompraItem != null)
            {
                if(carrinhoCompraItem.Quantidade > 1)
                {
                    carrinhoCompraItem.Quantidade--;
                    quantidadeLocal = carrinhoCompraItem.Quantidade;
                }
                else
                {
                    _context.CarrinhoCompraItens.Remove(carrinhoCompraItem);
                }
            }

            _context.SaveChanges();
            return quantidadeLocal;
        }

        public List<CarrinhoCompraItem> GetCarrinhoCompraItens()
        {
            return CarrinhoCompraItems ??
                (CarrinhoCompraItems =
                _context.CarrinhoCompraItens
                .Where(c => c.CarrinhoCompraId == CarrinhoCompraId)
                .Include(s => s.Roupa)
                .ToList());
        }

        public void LimparCarrinho()
        {
            var carrinhoItens = _context.CarrinhoCompraItens
                .Where(carrinho => carrinho.CarrinhoCompraId == CarrinhoCompraId);

            _context.CarrinhoCompraItens.RemoveRange(carrinhoItens);
            _context.SaveChanges();
        }

        public decimal GetCarrinhoCompraTotal()
        {
            var total = _context.CarrinhoCompraItens
                .Where(c => c.CarrinhoCompraId == CarrinhoCompraId)
                .Select(c => c.Roupa.Preco * c.Quantidade).Sum();

            return total;
        }
    }
}

ViewModels/CarrinhoCompraViewModel.cs
using NetPants.Models;

namespace NetPants.ViewModels
{
    public class CarrinhoCompraViewModel
    {
        public CarrinhoCompra CarrinhoCompra { get; set; }
        public decimal CarrinhoCompraTotal { get; set; }
    }
}

Controllers/CarrinhoCompraController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetPants.Models;
using NetPants.Repositories.Interfaces;
using NetPants.ViewModels;

namespace NetPants.Controllers
{
    public class CarrinhoCompraController : Controller
    {
        private readonly IRoupaRepository _roupaRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public CarrinhoCompraController(IRoupaRepository roupaRepository, 
            CarrinhoCompra carrinhoCompra)
        {
            _roupaRepository = roupaRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        public IActionResult Index()
        {
            var itens = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = itens;

            var carrinhoCompraVM = new CarrinhoCompraViewModel
            {
                CarrinhoCompra = _carrinhoCompra,
                CarrinhoCompraTotal = _carrinhoCompra.GetCarrinhoCompraTotal()
            };
            return View(carrinhoCompraVM);
        }

        [Authorize]
        public IActionResult AdicionarItemNoCarrinhoCompra(int roupaId)
        {
            var roupaSelecionada = _roupaRepository.Roupas.FirstOrDefault(p => p.RoupaId == roupaId);
            if(roupaSelecionada != null)
            {
                _carrinhoCompra.AdicionarAoCarrinho(roupaSelecionada);
            }
            return RedirectToAction("Index");
        }

        [Authorize]
        public IActionResult RemoverItemDoCarrinhoCompra(int roupaId)
        {
            var roupaSelecionada = _roupaRepository.Roupas.FirstOrDefault(p => p.RoupaId == roupaId);
            if (roupaSelecionada != null)
            {
                _carrinhoCompra.RemoverDoCarrinho(roupaSelecionada);
            }
            return RedirectToAction("Index");
        }
    }
}

Controllers/PedidoController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using NetPants.Models;
using NetPants.Repositories.Interfaces;

namespace NetPants.Controllers
{
    public class PedidoController : Controller
    {
        private readonly IPedidoRepository _pedidoRepository;
        private readonly CarrinhoCompra _carrinhoCompra;

        public PedidoController(IPedidoRepository pedidoRepository, CarrinhoCompra carrinhoCompra)
        {
            _pedidoRepository = pedidoRepository;
            _carrinhoCompra = carrinhoCompra;
        }

        [Authorize]
        [HttpGet]
        public IActionResult checkout()
        {
            return View();
        }

        [Authorize]
        [HttpPost]
        public IActionResult Checkout(Pedido pedido)
        {
            int totalItensPedido = 0;
            decimal precoTotalPedido = 0.0m;

            //Obter os itens do carrinho de compra do cliente
            List<CarrinhoCompraItem> items = _carrinhoCompra.GetCarrinhoCompraItens();
            _carrinhoCompra.CarrinhoCompraItems = items;

            //Verifica se existem itens de pedido
            if(_carrinhoCompra.CarrinhoCompraItems.Count == 0)
            {
                ModelState.AddModelError("", "Seu carrinho está vazio");
            }

            //Calcular o total de itens e calcular o total de pedidos
            foreach(var item in items)
            {
                totalItensPedido += item.Quantidade;
                precoTotalPedido += (item.Roupa.Preco * item.Quantidade);
            }

            //Atribuir os valores obtidos ao pedido
            pedido.TotalItensPedido = totalItensPedido;
            pedido.PedidoTotal = precoTotalPedido;


            //Validar os dados do pedido
            if (ModelState.IsValid)
            {
                //Cria o pedido e os detalhes
                _pedidoRepository.CriarPedido(pedido);


                //Define mensagem ao cliente
                ViewBag.CheckoutCompletoMensagem = "Obrigado pelo seu pedido";
                ViewBag.TotalPedido = _carrinhoCompra.GetCarrinhoCompraTotal();

                //Limpa o carrinho do cliente
                _carrinhoCompra.LimparCarrinho();


                //Exibe a view com dados do cliente e do pedido
                return View("~/Views/Pedido/CheckoutCompleto.cshtml", pedido);
            }
            return View(pedido);


        }

    }
}

Views/CarrinhoCompra/Index.cshtml
@model CarrinhoCompraViewModel

<div class="container">
    <div class="row" style="background-color:#CECECE; align-items: center; display: flex; justify-content: space-around; margin-top: 50px; padding-bottom: 50px">

        <div>
            <h3 style="display: flex; align-items:center; justify-content: space-around; padding: 70px 0">Sua Sacola</h3>
        </div>

        <table class="table table-bordered">
            <thead style="text-align:center;">
                <tr>
                    <th style="font-size: 22px">Produto(s) Escolhido(s)</th>
                    <th style="font-size: 22px">Quantidade</th>
                    <th style="font-size: 22px">Preço</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model.CarrinhoCompra.CarrinhoCompraItems)
                {
                    <tr>
                        <td class="text-center">@item.Roupa.DescricaoCurta</td>
                        <td class="text-center">@item.Quantidade</td>                       
                        <td class="text-center">@item.Roupa.Preco.ToString("c")</td>

                        <td class="text-center">
                            <a asp-controller="CarrinhoCompra" asp-action="RemoverItemDoCarrinhoCompra"
                           asp-route-roupaId="@item.Roupa.RoupaId">
                                <img src="~/images/lixeira.png" />
                            </a>
                        </td>
                    </tr>
                }
            </tbody>

            <tfoot>
                <tr>
                    <td class="text-center" style="text-transform: uppercase;"><b>Valor Total: </b></td>

                    <td class="text-center">
                        @Model.CarrinhoCompraTotal.ToString("c")
                    </td>
                </tr>
            </tfoot>
        </table>

        <div class="text-right">
            <div class="form-group" style="display: flex; align-items:center; justify-content: space-around; padding-top: 50px">
                <a class="btn btn-primary" asp-controller="Home" asp-action="Index">Continuar Comprando</a>
                <a class="btn btn-success" asp-controller="Pedido" asp-action="Checkout">Encerrar Pedido</a>
            </div>
        </div>

    </div>
</div>